In [1]:
import numpy as np
from linear_regression import SimpleLinearRegression, LinearRegression

In [2]:
x = np.array([1, 2, 3, 4, 5])
y = x * 2 + 3

In [3]:
model = SimpleLinearRegression()
model.fit(x, y)

In [4]:
y_pred = model.predict(x)

In [5]:
y_pred

array([ 5.,  7.,  9., 11., 13.])

In [6]:
y

array([ 5,  7,  9, 11, 13])

In [7]:
x_test = np.array([-1, -2, -3, -4, -5])
y_pred = model.predict(x_test)

In [8]:
y_pred

array([ 1., -1., -3., -5., -7.])

In [9]:
model.slope

np.float64(2.0)

In [10]:
model.intercept

np.float64(3.0)

In [2]:
X = np.array([[1, 2, 3],
              [-1, -2, -3],
              [2, 4, 6],
              [5, 1, 3],
              [9, 12, 5]])
weights = np.array([2, 3, 4]).T
y = X @ weights + 1

In [3]:
y

array([ 21, -19,  41,  26,  75])

In [4]:
-1*2+(-2*3)+(-3*4) + 1

-19

In [5]:
model2 = LinearRegression()
model2.fit(X, y)

In [6]:
model2.weights

array([1., 2., 3., 4.])