In [ ]:
import numpy as np
from linear_regression import SimpleLinearRegression

In [3]:
x = np.array([1, 2, 3, 4, 5])
y = x * 2 + 3

In [5]:
model = SimpleLinearRegression()
model.fit(x, y)

In [6]:
y_pred = model.predict(x)

In [7]:
y_pred

array([ 5.,  7.,  9., 11., 13.])

In [8]:
y

array([ 5,  7,  9, 11, 13])

In [10]:
x_test = np.array([-1, -2, -3, -4, -5])
y_pred = model.predict(x_test)

In [11]:
y_pred

array([ 1., -1., -3., -5., -7.])

In [12]:
model.slope

np.float64(2.0)

In [13]:
model.intercept

np.float64(3.0)